// src/vue/uplot-vue.tsx
import Vue, {PropType, VNode} from 'vue';

import uPlot from 'uplot';

import {optionsUpdateState, dataMatch} from '../common';

export default Vue.extend<
    {_chart: uPlot | null},
    {_destroy: () => void, _create: () => void},
    Record<string, never>,
    // eslint-disable-next-line
    {options: uPlot.Options, data: uPlot.AlignedData, target?: HTMLElement | ((self: uPlot, init: Function) => void)}
>({
    name: 'UPlotVue',
    props: {
        options: {type: Object as PropType<uPlot.Options>, required: true},
        data: {type: Array as unknown as PropType<uPlot.AlignedData>, required: true},
        target: {
            validator(target) {
                return target == null || target instanceof HTMLElement || typeof target === 'function';
            },
            default: undefined,
            required: false
        }
    },
    data(): {_chart: uPlot | null} {
        // eslint-disable-next-line
        return {_chart: null};
    },
    watch: {
        options(prevOptions: uPlot.Options, options: uPlot.Options) {
            const optionsState = optionsUpdateState(prevOptions, options);
            if (!this._chart || optionsState === 'create') {
                this._destroy();
                this._create();
            } else if (optionsState === 'update') {
                this._chart.setSize({width: options.width, height: options.height});
            }
        },
        target() {
            this._destroy();
            this._create();
        },
        data(prevData: uPlot.AlignedData, data: uPlot.AlignedData) {
            if (!this._chart) {
                this._create();
            } else if (!dataMatch(prevData, data)) {
                this._chart.setData(data);
            }
        }
    },
    mounted() {
        this._create();
    },
    beforeDestroy() {
        this._destroy();
    },
    methods: {
        _destroy() {
            if (this._chart) {
                this.$emit('delete', this._chart);
                this._chart.destroy();
                this._chart = null;
            }
        },
        _create() {
            this._chart = new uPlot(this.$props.options, this.$props.data, this.$props.target);
            this.$emit('create', this._chart);
        }
    },
    render() {
        return null as unknown as VNode;
    }
});

// react/uplot-react.tsx
import {useEffect, useRef} from 'react';

import uPlot from 'uplot';

import {optionsUpdateState, dataMatch} from 'uplot-wrappers-common';

export default function UplotReact({options, data, target, onDelete = () => {}, onCreate = () => {}}: {
    options: uPlot.Options,
    data: uPlot.AlignedData,
    // eslint-disable-next-line
    target?: HTMLElement | ((self: uPlot, init: Function) => void),
    onDelete?: (chart: uPlot) => void
    onCreate?: (chart: uPlot) => void
}): JSX.Element | null {
    const chartRef = useRef<uPlot | null>(null);

    function destroy(chart: uPlot | null) {
        if (chart) {
            onDelete(chart);
            chart.destroy();
            chartRef.current = null;
        }
    }
    function create() {
        const newChart = new uPlot(options, data, target)
        chartRef.current = newChart;
        onCreate(newChart);
    }
    // componentDidMount + componentWillUnmount
    useEffect(() => {
        create();
        return () => {
            destroy(chartRef.current);
        }
    }, []);
    // componentDidUpdate
    const prevProps = useRef({options, data, target}).current;
    useEffect(() => {
        const chart = chartRef.current;
        if (prevProps.options !== options) {
            const optionsState = optionsUpdateState(prevProps.options, options);
            if (!chart || optionsState === 'create') {
                destroy(chart);
                create();
            } else if (optionsState === 'update') {
                chart.setSize({width: options.width, height: options.height});
            }
        }
        if (prevProps.data !== data) {
            if (!chart) {
                create();
            } else if (!dataMatch(prevProps.data, data)) {
                chart.setData(data);
            }
        }
        if (prevProps.target !== target) {
            destroy(chart);
            create();
        }

        return () => {
            prevProps.options = options;
            prevProps.data = data;
            prevProps.target = target;
        };
    }, [options, data, target]);

    return null;
}
