// vue/uplot-vue3-example.tsx
// @ts-ignore
import {VNode, createApp} from 'vue';

import uPlot from 'uplot';
import 'uplot/dist/uPlot.min.css';

import UplotVue from 'uplot-vue';

const dummyPlugin = (): uPlot.Plugin => ({
    hooks: {
        init(u: uPlot, opts: uPlot.Options) {void u; void opts;}
    }
});

const app = createApp({
    name: 'UplotVueExample',
    components: {uplotvue: UplotVue},
    // @ts-ignore
    data() {
        return {
            options: {
                title: 'Chart', width: 400, height: 300,
                series: [{
                    label: 'Date'
                }, {
                    label: '',
                    points: {show: false},
                    stroke: 'blue',
                    fill: 'blue'
                }],
                plugins: [dummyPlugin()],
                scales: {x: {time: false}}
            },
            target: null as unknown as HTMLElement
        };
    },
    beforeMount() {
        // Initialize data inside mounted hook, to prevent Vue from adding watchers, otherwise performance becomes unbearable
        this.data = [[...new Array(100000)].map((_, i) => i), [...new Array(100000)].map((_, i) => i % 1000)];
    },
    mounted() {
        this.target = this.$refs.root as HTMLElement;
        setInterval(() => {
            const options = {
                ...this.options,
                title: (this.$refs.root as HTMLElement).id ? 'Rendered with template' : 'Rendered with function'
            };
            const data: uPlot.AlignedData = [
                [...this.data[0], this.data[0].length],
                [...this.data[1], this.data[0].length % 1000]
            ];
            this.data = data;
            // Since we disabled reactivity for data above
            this.$forceUpdate();
            this.options = options;
        }, 100);
    },
    render(): VNode {
        // @ts-ignore
        return (<div ref='root'>
            <UplotVue
                key="render-key"
                // @ts-ignore
                options={this.options}
                data={this.data}
                // Uncomment the line below to use predefined target
                // target={this.target}
                onDelete={(/* chart: uPlot */) => console.log('Deleted from render function')}
                onCreate={(/* chart: uPlot */) => console.log('Created from render function')}
            />
        </div>);
    }
});

// Render from render function
app.mount('#function-root');

// react/uplot-react-example.tsx
import React, {useMemo, useState} from 'react';
import ReactDOM, {unstable_batchedUpdates} from 'react-dom';

import uPlot from 'uplot';
import 'uplot/dist/uPlot.min.css';

import UPlotReact from './uplot-react';

const root: HTMLElement = document.querySelector('#root')!;

const dummyPlugin = (): uPlot.Plugin => ({
    hooks: {
        init(u: uPlot, opts: uPlot.Options) {void u; void opts;}
    }
});

class ClassApp extends React.Component<
    Record<string, never>,
    {options: uPlot.Options, data: uPlot.AlignedData}
> {
    constructor(args: Record<string, never>) {
        super(args);
        this.state = {
            options: {
                title: 'Chart',
                width: 400,
                height: 300,
                series: [{
                    label: 'Date'
                }, {
                    label: '',
                    points: {show: false},
                    stroke: 'blue',
                    fill: 'blue'
                }],
                scales: {x: {time: false}},
                plugins: [dummyPlugin()]
            },
            data: [[...new Array(100000)].map((_, i) => i), [...new Array(100000)].map((_, i) => i % 1000)]
        };
        setInterval(() => {
            const options = {
                ...this.state.options,
                title: 'Rendered with class'
            };
            const data: uPlot.AlignedData = [
                [...this.state.data[0], this.state.data[0].length],
                [...this.state.data[1], this.state.data[0].length % 1000]
            ];
            this.setState({data, options});
        }, 100);
    }
    render(): React.ReactNode {
        return (<UPlotReact
            key="class-key"
            options={this.state.options}
            data={this.state.data}
            // Uncomment the line below to use predefined target
            // target={root}
            onDelete={(/* chart: uPlot */) => console.log('Deleted from class')}
            onCreate={(/* chart: uPlot */) => console.log('Created from class')}
        />);
    }
}

const HooksApp = () => {
    const [options, setOptions] = useState<uPlot.Options>(useMemo(() => ({
        title: 'Chart',
        width: 400,
        height: 300,
        series: [{
            label: 'Date'
        }, {
            label: '',
            points: {show: false},
            stroke: 'blue',
            fill: 'blue'
        }],
        plugins: [dummyPlugin()],
        scales: {x: {time: false}}
    }), []));
    const initialState = useMemo<uPlot.AlignedData>(() =>
        ([[...new Array(100000)].map((_, i) => i), [...new Array(100000)].map((_, i) => i % 1000)])
    , []);
    const [data, setData] = useState<uPlot.AlignedData>(initialState);

    setTimeout(() => {
        const newOptions = {
            ...options,
            title: 'Rendered with hooks'
        };
        const newData: uPlot.AlignedData = [
            [...data[0], data[0].length],
            [...data[1], data[0].length % 1000]
        ];

        unstable_batchedUpdates(() => {
            setData(newData);
            setOptions(newOptions);
        });
    }, 100);
    return (<UPlotReact
        key="hooks-key"
        options={options}
        data={data}
        target={root}
        onDelete={(/* chart: uPlot */) => console.log('Deleted from hooks')}
        onCreate={(/* chart: uPlot */) => console.log('Created from hooks')}
    />);
}

ReactDOM.render(
    <React.Fragment>
        <HooksApp />
        <ClassApp />
    </React.Fragment>,
    root
);
