// src/react/uplot-react.tsx
import {useEffect, useRef, useState} from 'react';

import uPlot from 'uplot';

import {optionsUpdateState, dataMatch} from '../common';

export default function UplotReact({options, data, target, onDelete = () => {}, onCreate = () => {}}: {
    options: uPlot.Options,
    data: uPlot.AlignedData,
    target: HTMLElement,
    onDelete?: (chart: uPlot) => void
    onCreate?: (chart: uPlot) => void
}): JSX.Element | null {
    const [chart, setChart] = useState<uPlot | null>(null);

    function destroy(chart: uPlot | null) {
        if (chart) {
            onDelete(chart);
            chart.destroy();
            setChart(null);
        }
    }
    function create() {
        const newChart = new uPlot(options, data, target)
        setChart(newChart);
        onCreate(newChart);
    }
    // componentDidMount + componentWillUnmount
    useEffect(() => {
        create();
        return () => {
            destroy(chart);
        }
    }, []);
    // componentDidUpdate
    const prevProps = useRef({options, data, target}).current;
    useEffect(() => {
        if (prevProps.options !== options) {
            const optionsState = optionsUpdateState(prevProps.options, options);
            if (!chart || optionsState === 'create') {
                destroy(chart);
                create();
            } else if (optionsState === 'update') {
                chart.setSize({width: options.width, height: options.height});
            }
        }
        if (prevProps.data !== data) {
            if (!chart) {
                create();
            } else if (!dataMatch(prevProps.data, data)) {
                chart.setData(data);
            }
        }
        if (prevProps.target !== target) {
            destroy(chart);
            create();
        }

        return () => {
            prevProps.options = options;
            prevProps.data = data;
            prevProps.target = target;
        };
    }, [options, data, target]);

    return null;
}

// svelte/uplot-svelte.svelte
<script lang="ts">
    import uPlot from 'uplot';
    import { onDestroy, onMount } from 'svelte';
    import { optionsUpdateState } from 'uplot-wrappers-common';

    export let options: uPlot.Options;
    export let data: uPlot.AlignedData;
    export let target: HTMLDivElement | null = null;
    export let onDelete: (chart: uPlot) => void = () => {};
    export let onCreate: (chart: uPlot) => void = () => {};
    export let resetScales = true;

    let chart: uPlot | null = null;
    let div: HTMLDivElement;

    const destroy = () => {
        if (chart) {
            onDelete(chart);
            chart.destroy();
            chart = null;
        }
    };

    const create = () => {
        if (!chart) {
            chart = new uPlot(options, data, target || div);
            onCreate(chart);
        }
    };

    onMount(async () => {
        create();
    });

    onDestroy(() => {
        destroy();
    });

    let prevOptions: uPlot.Options = { ...options };

    $: {
        if (options) {
            const state = optionsUpdateState(prevOptions, options);
            prevOptions = { ...options };
            if (state === 'create') {
                destroy();
                create();
            } else if (state === 'update' && chart) {
                chart.setSize({
                    width: options.width,
                    height: options.height,
                });
            }
        }
    }

    $: if (target) {
        destroy();
        create();
    }

    $: {
        if (!chart) {
            create();
        } else if (resetScales) {
            chart.setData(data, true);
        } else {
            chart.setData(data, false);
            chart.redraw();
        }
    }
</script>

{#if !target}
    <div bind:this={div}></div>
{/if}
