// react/uplot-react.tsx
import React, { useCallback, useEffect, useRef } from 'react';

import uPlot from 'uplot';

import { optionsUpdateState, dataMatch } from 'uplot-wrappers-common';

export default function UplotReact({
    options,
    data,
    target,
    onDelete,
    onCreate,
    resetScales = true,
}: {
    options: uPlot.Options;
    data: uPlot.AlignedData;
    // eslint-disable-next-line
    target?: HTMLElement | ((self: uPlot, init: Function) => void);
    onDelete?: (chart: uPlot) => void;
    onCreate?: (chart: uPlot) => void;
    resetScales?: boolean;
}): JSX.Element | null {
    const chartRef = useRef<uPlot | null>(null);
    const targetRef = useRef<HTMLDivElement>(null);
    const propOptionsRef = useRef(options);
    const propTargetRef = useRef(target);
    const propDataRef = useRef(data);

    const destroy = useCallback(
        (chart: uPlot | null) => {
            if (chart) {
                onDelete?.(chart);
                chart.destroy();
                chartRef.current = null;
            }
        },
        [onDelete]
    );
    const create = useCallback(() => {
        const newChart = new uPlot(
            propOptionsRef.current,
            propDataRef.current,
            propTargetRef.current || (targetRef.current as HTMLDivElement)
        );
        chartRef.current = newChart;
        onCreate?.(newChart);
    }, [onCreate]);

    useEffect(() => {
        create();
        return () => {
            destroy(chartRef.current);
        };
    }, [create, destroy]);

    useEffect(() => {
        if (propOptionsRef.current !== options) {
            const optionsState = optionsUpdateState(propOptionsRef.current, options);
            propOptionsRef.current = options;
            if (!chartRef.current || optionsState === 'create') {
                destroy(chartRef.current);
                create();
            } else if (optionsState === 'update') {
                chartRef.current.setSize({
                    width: options.width,
                    height: options.height,
                });
            }
        }
    }, [options, create, destroy]);

    useEffect(() => {
        if (propDataRef.current !== data) {
            if (!chartRef.current) {
                propDataRef.current = data;
                create();
            } else if (!dataMatch(propDataRef.current, data)) {
                if (resetScales) {
                    chartRef.current.setData(data, true);
                } else {
                    chartRef.current.setData(data, false);
                    chartRef.current.redraw();
                }
            }
            propDataRef.current = data;
        }
    }, [data, resetScales, create]);

    useEffect(() => {
        if (propTargetRef.current !== target) {
            propTargetRef.current = target;
            create();
        }

        const chart = chartRef.current;
        return chart ? () => destroy(chart) : undefined;
    }, [target, create, destroy]);

    return target ? null : <div ref={targetRef}></div>;
}

// svelte/uplot-svelte.svelte
<script lang="ts">
    import uPlot from 'uplot';
    import { onDestroy, onMount } from 'svelte';
    import { optionsUpdateState } from 'uplot-wrappers-common';

    export let options: uPlot.Options;
    export let data: uPlot.AlignedData;
    export let target: HTMLDivElement | null = null;
    export let onDelete: (chart: uPlot) => void = () => {};
    export let onCreate: (chart: uPlot) => void = () => {};
    export let resetScales = true;

    let chart: uPlot | null = null;
    let div: HTMLDivElement;

    const destroy = () => {
        if (chart) {
            onDelete(chart);
            chart.destroy();
            chart = null;
        }
    };

    const create = () => {
        if (!chart) {
            chart = new uPlot(options, data, target || div);
            onCreate(chart);
        }
    };

    onMount(async () => {
        create();
    });

    onDestroy(() => {
        destroy();
    });

    let prevOptions: uPlot.Options = { ...options };

    $: {
        if (options) {
            const state = optionsUpdateState(prevOptions, options);
            prevOptions = { ...options };
            if (state === 'create') {
                destroy();
                create();
            } else if (state === 'update' && chart) {
                chart.setSize({
                    width: options.width,
                    height: options.height,
                });
            }
        }
    }

    $: if (target) {
        destroy();
        create();
    }

    $: {
        if (!chart) {
            create();
        } else if (resetScales) {
            chart.setData(data, true);
        } else {
            chart.setData(data, false);
            chart.redraw();
        }
    }
</script>

{#if !target}
    <div bind:this={div}></div>
{/if}
