// src/react/test-react.tsx
import React, {useState} from 'react';
import ReactDOM, {unstable_batchedUpdates} from 'react-dom';

import uPlot from 'uplot';
import UPlotReact from './uplot-react';

const root: HTMLElement = document.querySelector('#root')!;

class ClassApp extends React.Component<
    Record<string, never>,
    {options: uPlot.Options, data: uPlot.AlignedData}
> {
    constructor(args: Record<string, never>) {
        super(args);
        this.state = {
            options: {title: 'Chart', width: 400, height: 300, series: [{
                label: 'Date'
            }, {
                label: '',
                points: {show: false},
                stroke: 'blue',
                fill: 'blue'
            }],
                scales: {x: {time: false}}
            },
            data: [[0, 1, 3, 4, 5], [10, 20, 10, 0, 30]]
        };
        setInterval(() => {
            const rand = Math.round(Math.random() * 10);
            const options = {
                ...this.state.options,
                title: 'Rendered with class'
            };
            const data: uPlot.AlignedData = [...this.state.data];
            data[1] = [...data[1]];
            data[1][rand % (data[1].length - 1)] = rand * 3;
            this.setState({data, options});
        }, 2000);
    }
    render(): React.ReactNode {
        return (<UPlotReact
            options={this.state.options}
            data={this.state.data}
            target={root}
            onDelete={() => console.log('Deleted from class')}
            onCreate={() => console.log('Created form class')}
        />);
    }
}

const HooksApp = () => {
    const [options, setOptions] = useState<uPlot.Options>(
        {title: 'Chart', width: 400, height: 300, series: [{
            label: 'Date'
        }, {
            label: '',
            points: {show: false},
            stroke: 'blue',
            fill: 'blue'
        }],
        scales: {x: {time: false}}
    });
    const [data, setData] = useState<uPlot.AlignedData>([[0, 1, 3, 4, 5], [10, 20, 10, 0, 30]]);
    setTimeout(() => {
        const rand = Math.round(Math.random() * 10);
        const newOptions = {
            ...options,
            title: 'Rendered with hooks'
        };
        const newData: uPlot.AlignedData = [...data];
        newData[1] = [...newData[1]];
        newData[1][rand % (newData[1].length - 1)] = rand * 3;
        unstable_batchedUpdates(() => {
            setData(newData);
            setOptions(newOptions);
        });
    }, 2000);
    return (<UPlotReact
        options={options}
        data={data}
        target={root}
        onDelete={() => console.log('Deleted from hooks')}
        onCreate={() => console.log('Created from hooks')}
    />);
}

ReactDOM.render(
    <div>
        <HooksApp />,
        <ClassApp />
    </div>,
    root
);

// src/vue/test-vue.tsx
import Vue, {VNode, CreateElement} from 'vue';

import uPlot from 'uplot';

import UPlotVue from './vue';

const App = Vue.extend<
    {options: uPlot.Options, data: uPlot.AlignedData, target: HTMLElement},
    {onCreateFromTemplate: () => void, onDeleteFromTemplate: () => void},
    Record<string, never>, Record<string, never>
>({
    name: 'UPlotVueTest',
    components: {uplotvue: UPlotVue},
    data() {
        return {
            options: {
                title: 'Chart', width: 400, height: 300,
                series: [{
                    label: 'Date'
                }, {
                    label: '',
                    points: {show: false},
                    stroke: 'blue',
                    fill: 'blue'
                }],
                scales: {x: {time: false}}
            },
            data: [[0, 1, 3, 4, 5], [10, 20, 10, 0, 30]],
            target: null as unknown as HTMLElement
        };
    },
    mounted() {
        this.target = document.querySelector('#chart')/* this.$refs.root */ as HTMLElement;
        setInterval(() => {
            const rand = Math.round(Math.random() * 10);
            const options = {
                ...this.options,
                title: (this.$refs.root as HTMLElement).id ? 'Rendered with template' : 'Rendered with function'
            };
            const data: uPlot.AlignedData = [...this.data];
            data[1] = [...data[1]];
            data[1][rand % (data[1].length - 1)] = rand * 3;
            this.data = data;
            this.options = options;
        }, 2000);
    },
    methods: {
        onCreateFromTemplate() {
            console.log('Created from template');
        },
        onDeleteFromTemplate() {
            console.log('Deleted from template');
        }
    },
    // eslint-disable-next-line
    render(h: CreateElement): VNode {
        return (<div ref='root'>
            <UPlotVue
                // @ts-ignore
                options={this.options}
                data={this.data}
                target={this.target}
                onDelete={() => console.log('Deleted from render function')}
                onCreate={() => console.log('Created from render function')}
            />
        </div>);
    }
});

// Render from template
// @ts-ignore
new App({el: '#root', render: null});
// Render from render function
new App({el: '#root'});
