// src/test-react.tsx
import React, {useState} from 'react';
import ReactDOM from 'react-dom';

import uPlot from 'uplot';
import UplotReact from 'uplot-wrappers';

let series = [{
    label: 'Date'
  }, {
    label: '',
    points: {show: false},
    stroke: 'blue',
    fill: 'blue'
  }
]

const root: HTMLElement = document.querySelector('#root')!;

let options = {width: 800, height: 600, series};
let data: uPlot.AlignedData = [[0, 1, 3, 4, 5], [10, 20, 10, 0, 30]];

class ClassApp extends React.Component<Record<string, never>, {updater: number}> {
    constructor(args: Record<string, never>) {
        super(args);
        this.state = {updater: 0};
        setInterval(() => {
            series = [...series];
            series[0] = {label: 'Date' + Math.random() * 10};
            options = {...options, series, width: options.width - 5};
            data = [...data];
            data[1][0] = Math.random() * 10;
            this.setState({updater: this.state.updater + Math.random()});
        }, 1000);
    }
    render(): React.ReactNode {
        return <UplotReact options={options} data={data} target={root} onDelete={() => console.log('Deleted2')} onCreate={() => console.log('Created2')}/>
    }
}

const App = () => {
    const [updater, setUpdater] = useState(0);
    setTimeout(() => {
        series = [...series];
        series[0] = {label: 'Date' + Math.random() * 10};
        options = {...options, series, width: options.width - 5};
        data = [...data];
        data[1][0] = Math.random() * 10;
        setUpdater(updater + Math.random());
    }, 1000);
    return <UplotReact options={options} data={data} target={root} onDelete={() => console.log('Deleted')} onCreate={() => console.log('Created')}/>
}

ReactDOM.render(
    <div>
        <App />,
        <ClassApp />
    </div>,
    root
);

// src/test-vue.tsx
import Vue, {CreateElement, VNode} from 'vue';

import uPlot from 'uplot';
import uPlotVue from 'uplot-wrappers';

const App = Vue.extend<{options: uPlot.Options, data: uPlot.AlignedData, target: HTMLElement}, {}, {}, {}>({
    components: {uplotvue: uPlotVue},
    name: 'uPlotVueTest',
    data() {
        console.log(this);
        return {
            // @ts-ignore
            options: {title: 'Chart', width: 400, height: 300,
                series: [{
                    label: 'Date'
                }, {
                    label: '',
                    points: {show: false},
                    stroke: 'blue',
                    fill: 'blue'
                }],
                scales: {x: {time: false}}
            },
            data: [[0, 1, 3, 4, 5], [10, 20, 10, 0, 30]],
            target: null as unknown as HTMLElement
        };
    },
    methods: {
        onCreateFromTemplate() {
            console.log('Created from template');
        },
        onDeleteFromTemplate() {
            console.log('Deleted from template');
        }
    },
    render(h: CreateElement): VNode {
        // @ts-ignore
        return (<div ref='root'>
            <uPlotVue
                ref='root'
                options={this.options}
                data={this.data}
                target={this.target}
                onDelete={() => console.log('Deleted from render')}
                onCreate={() => console.log('Created from render')}
            />
        </div>) as unknown as VNode;
    },
    mounted() {
        this.target = document.querySelector('#chart')/* this.$refs.root */ as HTMLElement;
        setInterval(() => {
            const series = [...this.options.series];
            const rand = Math.round(Math.random() * 10);
            // series[0] = {label: 'Date ' + rand};
            const options = {
                ...this.options,
                title: (this.$refs.root as any).id ? 'Rendered from template' : 'Rendered from function',
                series/* ,
                width: this.options.width - (15 * rand > 5 ? -1 : 1) */
            };
            const data: uPlot.AlignedData = [...this.data];
            data[1] = [...data[1]];
            data[1][rand % (data[1].length - 1)] = rand * 3;
            this.data = data;
            this.options = options;
        }, 2000);
    }
});

// Render from template
// @ts-ignore
new App({el: '#root', render: null});
// Render from render function
new App({el: '#root'});
